import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const RESERVED_SCHEMA_ORIGIN = "https://aerial-rescue.invalid";
const RESERVED_SCHEMA_PREFIX = "/schemas/v1/";
const GENERATED_BANNER = `/**
 * Generated from the committed dashboard JSON Schemas.
 * Do not edit this file by hand; run pnpm contracts:generate.
 */`;

interface DashboardSchemaDefinition {
  readonly fileName: string;
  readonly schemaId: string;
  readonly typeName: string;
}

interface ResolverFile {
  readonly url: string;
}

interface SchemaCompilerOptions {
  readonly $refOptions: {
    readonly resolve: {
      readonly file: false;
      readonly http: false;
      readonly repository: {
        readonly canRead: (file: ResolverFile) => boolean;
        readonly order: number;
        readonly read: (file: ResolverFile) => Promise<GeneratorSchema>;
      };
    };
  };
  readonly additionalProperties: false;
  readonly bannerComment: string;
  readonly cwd: string;
  readonly customName: (schema: GeneratorSchema) => string | undefined;
  readonly declareExternallyReferenced: true;
  readonly enableConstEnums: false;
  readonly format: true;
  readonly ignoreMinAndMaxItems: true;
  readonly strictIndexSignatures: true;
  readonly style: {
    readonly bracketSpacing: true;
    readonly printWidth: number;
    readonly semi: true;
    readonly singleQuote: false;
    readonly trailingComma: "all";
  };
  readonly unknownAny: true;
}

type GeneratorSchema = Record<string, unknown>;
type SchemaCompiler = (
  schema: GeneratorSchema,
  name: string,
  options: SchemaCompilerOptions,
) => Promise<string>;

const dashboardSchemas = [
  {
    fileName: "bootstrap",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/bootstrap.schema.json`,
    typeName: "DashboardBootstrap",
  },
  {
    fileName: "command-response",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/command-response.schema.json`,
    typeName: "DashboardCommandResponse",
  },
  {
    fileName: "dashboard-event-frame",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/dashboard-event-frame.schema.json`,
    typeName: "DashboardEventFrame",
  },
  {
    fileName: "dashboard-event",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/dashboard-event.schema.json`,
    typeName: "DashboardEvent",
  },
  {
    fileName: "dashboard-reduced-state",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/dashboard-reduced-state.schema.json`,
    typeName: "DashboardReducedState",
  },
  {
    fileName: "dashboard-snapshot",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/dashboard-snapshot.schema.json`,
    typeName: "DashboardSnapshot",
  },
  {
    fileName: "error",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/error.schema.json`,
    typeName: "DashboardError",
  },
  {
    fileName: "health",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/health.schema.json`,
    typeName: "DashboardHealth",
  },
  {
    fileName: "mutation-outcome",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/mutation-outcome.schema.json`,
    typeName: "DashboardMutationOutcome",
  },
  {
    fileName: "ordered-dashboard-event",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/ordered-dashboard-event.schema.json`,
    typeName: "OrderedDashboardEvent",
  },
  {
    fileName: "operator-command-request",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/operator-command-request.schema.json`,
    typeName: "DashboardOperatorCommandRequest",
  },
  {
    fileName: "proposal-decision-request",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/proposal-decision-request.schema.json`,
    typeName: "DashboardProposalDecisionRequest",
  },
  {
    fileName: "proposal-decision-response",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/proposal-decision-response.schema.json`,
    typeName: "DashboardProposalDecisionResponse",
  },
  {
    fileName: "readiness",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/readiness.schema.json`,
    typeName: "DashboardReadiness",
  },
  {
    fileName: "replay-bundle",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/replay-bundle.schema.json`,
    typeName: "DashboardReplayBundle",
  },
  {
    fileName: "replay-integrity",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/replay-integrity.schema.json`,
    typeName: "DashboardReplayIntegrity",
  },
  {
    fileName: "reset-request",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/reset-request.schema.json`,
    typeName: "DashboardResetRequest",
  },
  {
    fileName: "reset-response",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/reset-response.schema.json`,
    typeName: "DashboardResetResponse",
  },
  {
    fileName: "scenario-catalog",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/scenario-catalog.schema.json`,
    typeName: "DashboardScenarioCatalog",
  },
  {
    fileName: "source-signal",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/source-signal.schema.json`,
    typeName: "DashboardSourceSignal",
  },
  {
    fileName: "start-request",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/start-request.schema.json`,
    typeName: "DashboardStartRequest",
  },
  {
    fileName: "start-response",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/start-response.schema.json`,
    typeName: "DashboardStartResponse",
  },
  {
    fileName: "stream-overloaded",
    schemaId: `${RESERVED_SCHEMA_ORIGIN}${RESERVED_SCHEMA_PREFIX}dashboard/stream-overloaded.schema.json`,
    typeName: "DashboardStreamOverloaded",
  },
] as const satisfies readonly DashboardSchemaDefinition[];

const dashboardRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const schemaRoot = resolve(dashboardRoot, "../../schemas/v1");
const dashboardSchemaRoot = resolve(schemaRoot, "dashboard");
const generatedRoot = resolve(dashboardRoot, "src/contracts/generated");
const knownTypeNames: ReadonlyMap<string, string> = new Map(
  dashboardSchemas.map(({ schemaId, typeName }) => [schemaId, typeName] as const),
);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function loadSchemaCompiler(): SchemaCompiler {
  const require = createRequire(import.meta.url);
  const compilerModule: unknown = require("json-schema-to-typescript");
  if (!isRecord(compilerModule) || typeof compilerModule["compile"] !== "function") {
    throw new TypeError("json-schema-to-typescript does not expose its compile function");
  }
  const compiler = compilerModule["compile"];
  return async (schema, name, options) => {
    const output: unknown = await Reflect.apply(compiler, undefined, [schema, name, options]);
    if (typeof output !== "string") {
      throw new TypeError("json-schema-to-typescript returned a non-string result");
    }
    return output;
  };
}

const compileSchema = loadSchemaCompiler();

function normalizeReferenceSiblings(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((member) => normalizeReferenceSiblings(member));
  }
  if (!isRecord(value)) {
    return value;
  }

  const normalized = Object.fromEntries(
    Object.entries(value).map(([key, member]) => [key, normalizeReferenceSiblings(member)]),
  );
  const reference = normalized["$ref"];
  if (typeof reference !== "string" || Object.keys(normalized).length === 1) {
    return normalized;
  }

  const siblings = Object.fromEntries(Object.entries(normalized).filter(([key]) => key !== "$ref"));
  return { allOf: [{ $ref: reference }, siblings] };
}

function parseSchema(raw: string, source: string): GeneratorSchema {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw) as unknown;
  } catch (error: unknown) {
    throw new Error(`Cannot parse schema ${source}`, { cause: error });
  }
  if (!isRecord(parsed)) {
    throw new TypeError(`Schema ${source} must contain a JSON object`);
  }
  return normalizeReferenceSiblings(parsed) as GeneratorSchema;
}

function resolveReservedSchemaPath(url: string): string {
  const parsed = new URL(url);
  if (
    parsed.origin !== RESERVED_SCHEMA_ORIGIN ||
    parsed.username !== "" ||
    parsed.password !== "" ||
    parsed.search !== "" ||
    !parsed.pathname.startsWith(RESERVED_SCHEMA_PREFIX)
  ) {
    throw new Error(`Refusing non-repository schema reference: ${url}`);
  }

  const relativePath = decodeURIComponent(parsed.pathname.slice(RESERVED_SCHEMA_PREFIX.length));
  const candidate = resolve(schemaRoot, relativePath);
  const candidateRelativePath = relative(schemaRoot, candidate);
  if (
    candidateRelativePath === "" ||
    candidateRelativePath.startsWith("..") ||
    isAbsolute(candidateRelativePath) ||
    !candidate.endsWith(".schema.json")
  ) {
    throw new Error(`Refusing schema reference outside the v1 schema root: ${url}`);
  }
  return candidate;
}

async function readReservedSchema(url: string): Promise<GeneratorSchema> {
  const schemaPath = resolveReservedSchemaPath(url);
  const raw = await readFile(schemaPath, "utf8");
  return parseSchema(raw, schemaPath);
}

function generatedIndex(): string {
  const imports = dashboardSchemas
    .map(({ fileName, typeName }) => `import type { ${typeName} } from "./${fileName}";`)
    .join("\n");
  const exports = dashboardSchemas
    .map(({ fileName, typeName }) => `export type { ${typeName} } from "./${fileName}";`)
    .join("\n");
  const schemaMapping = dashboardSchemas
    .map(({ schemaId, typeName }) => `  readonly "${schemaId}": ${typeName};`)
    .join("\n");

  return `${GENERATED_BANNER}\n\n${imports}\n\n${exports}\n\nexport interface DashboardDocumentBySchemaId {\n${schemaMapping}\n}\n`;
}

async function generateSchema(definition: DashboardSchemaDefinition): Promise<string> {
  const schemaPath = resolve(dashboardSchemaRoot, `${definition.fileName}.schema.json`);
  const parsedSchema = parseSchema(await readFile(schemaPath, "utf8"), schemaPath);
  const schema =
    definition.fileName === "reset-request"
      ? { ...parsedSchema, tsType: "Record<PropertyKey, never>" }
      : parsedSchema;
  const generated = await compileSchema(schema, definition.typeName, {
    $refOptions: {
      resolve: {
        file: false,
        http: false,
        repository: {
          order: 1,
          canRead: (file) => file.url.startsWith(`${RESERVED_SCHEMA_ORIGIN}/`),
          read: async (file) => readReservedSchema(file.url),
        },
      },
    },
    additionalProperties: false,
    bannerComment: GENERATED_BANNER,
    cwd: dashboardSchemaRoot,
    customName: (linkedSchema) => {
      const schemaId = linkedSchema["$id"];
      return typeof schemaId === "string" ? knownTypeNames.get(schemaId) : undefined;
    },
    declareExternallyReferenced: true,
    enableConstEnums: false,
    format: true,
    ignoreMinAndMaxItems: true,
    strictIndexSignatures: true,
    style: {
      bracketSpacing: true,
      printWidth: 100,
      semi: true,
      singleQuote: false,
      trailingComma: "all",
    },
    unknownAny: true,
  });
  return generated.endsWith("\n") ? generated : `${generated}\n`;
}

async function assertSourceInventory(): Promise<void> {
  const expected = dashboardSchemas.map(({ fileName }) => `${fileName}.schema.json`).sort();
  const actual = (await readdir(dashboardSchemaRoot))
    .filter((entry) => entry.endsWith(".schema.json"))
    .sort();
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    throw new Error(
      `Dashboard schema inventory differs: expected ${expected.join(", ")}; found ${actual.join(", ")}`,
    );
  }
}

async function expectedOutputs(): Promise<ReadonlyMap<string, string>> {
  await assertSourceInventory();
  const generatedSchemas = await Promise.all(
    dashboardSchemas.map(
      async (definition) =>
        [`${definition.fileName}.ts`, await generateSchema(definition)] as const,
    ),
  );
  return new Map([...generatedSchemas, ["index.ts", generatedIndex()]]);
}

async function currentGeneratedEntries(): Promise<readonly string[]> {
  try {
    return (await readdir(generatedRoot)).sort();
  } catch (error: unknown) {
    if (isRecord(error) && error["code"] === "ENOENT") {
      return [];
    }
    throw error;
  }
}

async function refuseUnexpectedGeneratedEntries(expectedNames: readonly string[]): Promise<void> {
  const expected = new Set(expectedNames);
  const extras = (await currentGeneratedEntries()).filter((entry) => !expected.has(entry));
  if (extras.length > 0) {
    throw new Error(`Unexpected generated contract entries: ${extras.join(", ")}`);
  }
}

async function writeOutputs(outputs: ReadonlyMap<string, string>): Promise<void> {
  await refuseUnexpectedGeneratedEntries([...outputs.keys()]);
  await mkdir(generatedRoot, { recursive: true });
  await Promise.all(
    [...outputs].map(async ([fileName, contents]) =>
      writeFile(resolve(generatedRoot, fileName), contents, "utf8"),
    ),
  );
}

async function checkOutputs(outputs: ReadonlyMap<string, string>): Promise<void> {
  const expectedNames = [...outputs.keys()].sort();
  const actualNames = await currentGeneratedEntries();
  const missing = expectedNames.filter((entry) => !actualNames.includes(entry));
  const extra = actualNames.filter((entry) => !outputs.has(entry));
  const different: string[] = [];

  for (const [fileName, expected] of outputs) {
    if (missing.includes(fileName)) {
      continue;
    }
    const actual = await readFile(resolve(generatedRoot, fileName), "utf8");
    if (actual !== expected) {
      different.push(fileName);
    }
  }

  if (missing.length > 0 || extra.length > 0 || different.length > 0) {
    throw new Error(
      [
        `Generated dashboard contracts are stale.`,
        `Missing: ${missing.join(", ") || "none"}.`,
        `Different: ${different.join(", ") || "none"}.`,
        `Extra: ${extra.join(", ") || "none"}.`,
      ].join(" "),
    );
  }
}

async function main(): Promise<void> {
  const [mode, ...unexpectedArguments] = process.argv.slice(2);
  if ((mode !== "--write" && mode !== "--check") || unexpectedArguments.length > 0) {
    throw new Error("Usage: generate-dashboard-contracts.ts --write|--check");
  }

  const outputs = await expectedOutputs();
  if (mode === "--write") {
    await writeOutputs(outputs);
  } else {
    await checkOutputs(outputs);
  }
}

await main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : "Unknown contract-generation failure";
  console.error(message);
  process.exitCode = 1;
});
